-- MySQL Script generated by MySQL Workbench
-- Thu May 21 02:21:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Labrory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Labrory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Labrory` DEFAULT CHARACTER SET utf8 ;
USE `Labrory` ;

-- -----------------------------------------------------
-- Table `Labrory`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Labrory`.`Authors` (
  `ID_Author` INT NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(50) NOT NULL,
  `Last_name` VARCHAR(50) NOT NULL,
  `Birth_year` INT NULL,
  `Country` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_Author`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Labrory`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Labrory`.`Books` (
  `ID_Books` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `ISBN` VARCHAR(20) NULL,
  `Publication_year` INT NULL,
  `Price` DECIMAL(8,2) NULL,
  `ID_Author` INT NULL,
  PRIMARY KEY (`ID_Books`),
  INDEX `AuthorToBooks_idx` (`ID_Author` ASC) VISIBLE,
  CONSTRAINT `AuthorToBooks`
    FOREIGN KEY (`ID_Author`)
    REFERENCES `Labrory`.`Authors` (`ID_Author`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Labrory`.`Readers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Labrory`.`Readers` (
  `ID_Reader` INT NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Registration_date` DATE NULL,
  `Adress` TEXT NULL,
  PRIMARY KEY (`ID_Reader`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Labrory`.`BookLoans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Labrory`.`BookLoans` (
  `ID_BookLoans` INT NOT NULL AUTO_INCREMENT,
  `ID_Books` INT NOT NULL,
  `ID_Reader` INT NOT NULL,
  `Loan_date` DATE NOT NULL,
  `Due_date` DATE NOT NULL,
  `Return_date` DATE NULL,
  `Loan_status` VARCHAR(20) NULL,
  `Fine_amount` DECIMAL(8,2) NULL,
  PRIMARY KEY (`ID_BookLoans`),
  INDEX `ID_Book_To_BookLoans_idx` (`ID_Books` ASC) VISIBLE,
  INDEX `ID_Readerr_To_BookLoans_idx` (`ID_Reader` ASC) VISIBLE,
  CONSTRAINT `BookToBookLoans`
    FOREIGN KEY (`ID_Books`)
    REFERENCES `Labrory`.`Books` (`ID_Books`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ReaderToBookLoans`
    FOREIGN KEY (`ID_Reader`)
    REFERENCES `Labrory`.`Readers` (`ID_Reader`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `Labrory`.`Authors`
-- -----------------------------------------------------
START TRANSACTION;
USE `Labrory`;
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (1, 'Лев', 'Толстой', 1828, 'Россия');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (2, 'Федор', 'Достоевский', 1821, 'Россия');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (3, 'Антон', 'Чехов', 1860, 'Россия');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (4, 'Александр', 'Пушкин', 1799, 'Россия');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (5, 'Михаил', 'Булгаков', 1891, 'Россия');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (6, 'Джордж', 'Оруэлл', 1903, 'Великобритания');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (7, 'Олдос', 'Хаксли', 1894, 'Великобритания');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (8, 'Рей', 'Брэдбери', 1920, 'США');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (9, 'Эрнест', 'Хемингуэй', 1899, 'США');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (10, 'Фрэнсис', 'Фицджеральд', 1896, 'США');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (11, 'Габриэль', 'Маркес', 1927, 'Колумбия');
INSERT INTO `Labrory`.`Authors` (`ID_Author`, `First_name`, `Last_name`, `Birth_year`, `Country`) VALUES (12, 'Харпер', 'Ли', 1926, 'США');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Labrory`.`Books`
-- -----------------------------------------------------
START TRANSACTION;
USE `Labrory`;
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (1, 'Война и мир', '978-5-389-07435-4', 1869, 1500.00, 1);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (2, 'Анна Каренина', '978-5-04-103496-9', 1877, 1200.00, 1);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (3, 'Воскресение', '978-5-17-090764-9', 1899, 900.00, 1);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (4, 'Преступление и наказание', '978-5-17-087888-8', 1866, 950.00, 2);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (5, 'Братья Карамазовы', '978-5-17-090140-1', 1880, 1100.00, 2);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (6, 'Идиот', '978-5-389-05738-8', 1869, 1000.00, 2);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (7, 'Вишневый сад', '978-5-389-05739-5', 1904, 600.00, 3);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (8, 'Дама с собачкой', '978-5-389-08331-8', 1899, 550.00, 3);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (9, 'Три сестры', '978-5-389-04816-3', 1901, 580.00, 3);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (10, 'Евгений Онегин', '978-5-389-04815-6', 1833, 800.00, 4);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (11, 'Капитанская дочка', '978-5-389-05740-1', 1836, 750.00, 4);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (12, 'Мастер и Маргарита', '978-5-17-090763-2', 1967, 1300.00, 5);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (13, 'Собачье сердце', '978-5-389-04817-0', 1925, 850.00, 5);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (14, '1984', '978-5-17-100939-7', 1949, 900.00, 6);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (15, 'Скотный двор', '978-5-17-080115-5', 1945, 750.00, 6);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (16, 'О дивный новый мир', '978-5-17-100938-0', 1932, 850.00, 7);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (17, '451 градус по Фаренгейту', '978-5-17-090055-8', 1953, 950.00, 8);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (18, 'Старик и море', '978-5-17-090056-5', 1952, 700.00, 9);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (19, 'Великий Гэтсби', '978-5-17-090057-2', 1925, 880.00, 10);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (20, 'Сто лет одиночества', '978-5-17-090058-9', 1967, 1100.00, 11);
INSERT INTO `Labrory`.`Books` (`ID_Books`, `Title`, `ISBN`, `Publication_year`, `Price`, `ID_Author`) VALUES (21, 'Убить пересмешника', '978-5-17-090059-6', 1960, 920.00, 12);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Labrory`.`Readers`
-- -----------------------------------------------------
START TRANSACTION;
USE `Labrory`;
INSERT INTO `Labrory`.`Readers` (`ID_Reader`, `First_name`, `Last_name`, `Email`, `Phone`, `Registration_date`, `Adress`) VALUES (1, 'Иван', 'Петров', 'ivan.petrov@mail.ru', '+79161234567', '2020-11-05', 'ул. Ленина, 25, кв. 12');
INSERT INTO `Labrory`.`Readers` (`ID_Reader`, `First_name`, `Last_name`, `Email`, `Phone`, `Registration_date`, `Adress`) VALUES (2, 'Мария', 'Сидорова', 'maria.sidorova@gmail.com', '+79162345678', '2021-09-18', 'пр. Мира, 48, кв. 34');
INSERT INTO `Labrory`.`Readers` (`ID_Reader`, `First_name`, `Last_name`, `Email`, `Phone`, `Registration_date`, `Adress`) VALUES (3, 'Алексей', 'Козлов', 'alex.kozlov@yandex.ru', '+79163456789', '2019-12-01', 'ул. Садовая, 15, кв. 7');
INSERT INTO `Labrory`.`Readers` (`ID_Reader`, `First_name`, `Last_name`, `Email`, `Phone`, `Registration_date`, `Adress`) VALUES (4, 'Елена', 'Никитина', 'elena.nikitina@mail.ru', '+79164567890', '2020-08-20', 'ул. Центральная, 89, кв. 56');
INSERT INTO `Labrory`.`Readers` (`ID_Reader`, `First_name`, `Last_name`, `Email`, `Phone`, `Registration_date`, `Adress`) VALUES (5, 'Дмитрий', 'Волков', 'dmitry.volkov@gmail.com', '+79165678901', '2021-06-14', 'пр. Строителей, 12, кв. 23');
INSERT INTO `Labrory`.`Readers` (`ID_Reader`, `First_name`, `Last_name`, `Email`, `Phone`, `Registration_date`, `Adress`) VALUES (6, 'Ольга', 'Семенова', 'olga.semenova@yandex.ru', '+79166789012', '2022-02-28', 'ул. Молодежная, 34, кв. 45');
INSERT INTO `Labrory`.`Readers` (`ID_Reader`, `First_name`, `Last_name`, `Email`, `Phone`, `Registration_date`, `Adress`) VALUES (7, 'Сергей', 'Павлов', 'sergey.pavlov@mail.ru', '+79167890123', '2021-04-10', 'ул. Школьная, 67, кв. 78');
INSERT INTO `Labrory`.`Readers` (`ID_Reader`, `First_name`, `Last_name`, `Email`, `Phone`, `Registration_date`, `Adress`) VALUES (8, 'Наталья', 'Федорова', 'natalia.fedorova@gmail.com', '+79168901234', '2023-02-15', 'пр. Победы, 90, кв. 11');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Labrory`.`BookLoans`
-- -----------------------------------------------------
START TRANSACTION;
USE `Labrory`;
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (1, 1, 1, '2023-09-01', '2023-09-15', '2023-09-14', 'Возвращено', 0.00);
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (2, 3, 2, '2023-09-05', '2023-09-19', NULL, 'Активнно', 0.00);
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (3, 8, 3, '2023-08-20', '2023-09-03', NULL, 'Просрочено', 150.00);
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (4, 5, 4, '2023-09-10', '2023-09-24', NULL, 'Активнно', 0.00);
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (5, 10, 5, '2023-08-25', '2023-09-08', '2023-09-07', 'Возвращено', 0.00);
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (6, 12, 6, '2023-09-03', '2023-09-17', NULL, 'Активнно', 0.00);
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (7, 15, 7, '2023-08-15', '2023-08-29', '2023-08-30', 'Возвращено', 50.00);
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (8, 18, 8, '2023-09-08', '2023-09-22', NULL, 'Активнно', 0.00);
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (9, 2, 1, '2023-09-12', '2023-09-26', NULL, 'Активнно', 0.00);
INSERT INTO `Labrory`.`BookLoans` (`ID_BookLoans`, `ID_Books`, `ID_Reader`, `Loan_date`, `Due_date`, `Return_date`, `Loan_status`, `Fine_amount`) VALUES (10, 7, 3, '2023-08-28', '2023-09-11', NULL, 'Просрочено', 100.00);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
